# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.cache/wt [current_project]
set_property parent.project_path C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/YANGQING/Desktop/open-hust-verilog-master/integer_to_segment.v
  C:/Users/YANGQING/Desktop/open-hust-verilog-master/data_to_segment.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/CP0.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/ROM.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/RAM.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/RegFile.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/ALU.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/ControlUnit.v
  C:/Users/YANGQING/Desktop/open-hust-verilog-master/tick_divider.v
  C:/Users/YANGQING/Desktop/open-hust-verilog-master/led_unit.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/IF.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/HazardUnit.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/WB.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/MEM_WB.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/MEM.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/IF_ID.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/ID_EX.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/ID.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/EX_MEM.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/EX.v
  C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/sources_1/new/MIPS_CPU.v
}
read_xdc C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/constrs_1/new/yingjiao.xdc
set_property used_in_implementation false [get_files C:/Users/YANGQING/Desktop/computer/MIPS_CPU/MIPS_CPU.srcs/constrs_1/new/yingjiao.xdc]

synth_design -top MIPS_CPU -part xc7a100tcsg324-1
write_checkpoint -noxdef MIPS_CPU.dcp
catch { report_utilization -file MIPS_CPU_utilization_synth.rpt -pb MIPS_CPU_utilization_synth.pb }
